/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as FreshnessRouteImport } from './routes/freshness'
import { Route as OwnerSetupRouteImport } from './routes/owner-setup'
import { Route as PosRouteImport } from './routes/pos'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ZizoRouteImport } from './routes/zizo'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBundlesRouteImport } from './routes/admin.bundles'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'
import { Route as AdminCatalogImportRouteImport } from './routes/admin.catalog-import'
import { Route as AdminDeliveryRouteImport } from './routes/admin.delivery'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminPromotionsRouteImport } from './routes/admin.promotions'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as DeveloperIndexRouteImport } from './routes/developer.index'
import { Route as DeveloperNewRouteImport } from './routes/developer.new'
import { Route as PosIndexRouteImport } from './routes/pos.index'
import { Route as PosCustomersRouteImport } from './routes/pos.customers'
import { Route as PosInventoryRouteImport } from './routes/pos.inventory'
import { Route as PosInvoicesRouteImport } from './routes/pos.invoices'
import { Route as PosPurchasesRouteImport } from './routes/pos.purchases'
import { Route as PosReportsRouteImport } from './routes/pos.reports'
import { Route as PosSuppliersRouteImport } from './routes/pos.suppliers'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as SStoreSlugRouteImport } from './routes/s.$storeSlug'
import { Route as TrackTokenRouteImport } from './routes/track.$token'
import { Route as AdminCatalogIdRouteImport } from './routes/admin.catalog.$id'
import { Route as AdminOrdersTokenRouteImport } from './routes/admin.orders.$token'
import { Route as DeveloperStoresIndexRouteImport } from './routes/developer.stores.index'
import { Route as DeveloperStoresIdRouteImport } from './routes/developer.stores.$id'
import { Route as OrderPendingTokenRouteImport } from './routes/order.pending.$token'
import { Route as SStoreSlugIndexRouteImport } from './routes/s.$storeSlug.index'
import { Route as SStoreSlugAdminRouteImport } from './routes/s.$storeSlug.admin'
import { Route as SStoreSlugCartRouteImport } from './routes/s.$storeSlug.cart'
import { Route as SStoreSlugCheckoutRouteImport } from './routes/s.$storeSlug.checkout'
import { Route as ApiPublicProductImageIdRouteImport } from './routes/api/public/product-image.$id'
import { Route as ApiPublicStoreLogoIdRouteImport } from './routes/api/public/store-logo.$id'
import { Route as SStoreSlugAdminIndexRouteImport } from './routes/s.$storeSlug.admin.index'
import { Route as SStoreSlugAdminAnnouncementsRouteImport } from './routes/s.$storeSlug.admin.announcements'
import { Route as SStoreSlugAdminCatalogRouteImport } from './routes/s.$storeSlug.admin.catalog'
import { Route as SStoreSlugAdminDeliveryRouteImport } from './routes/s.$storeSlug.admin.delivery'
import { Route as SStoreSlugAdminOrdersRouteImport } from './routes/s.$storeSlug.admin.orders'
import { Route as SStoreSlugAdminReportsRouteImport } from './routes/s.$storeSlug.admin.reports'
import { Route as SStoreSlugAdminSettingsRouteImport } from './routes/s.$storeSlug.admin.settings'
import { Route as SStoreSlugAdminTeamRouteImport } from './routes/s.$storeSlug.admin.team'
import { Route as SStoreSlugAdminThemeRouteImport } from './routes/s.$storeSlug.admin.theme'
import { Route as SStoreSlugOrderTokenRouteImport } from './routes/s.$storeSlug.order.$token'
import { Route as SStoreSlugProductSlugRouteImport } from './routes/s.$storeSlug.product.$slug'
import { Route as SStoreSlugTrackTokenRouteImport } from './routes/s.$storeSlug.track.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const FreshnessRoute = FreshnessRouteImport.update({
  id: '/freshness',
  path: '/freshness',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSetupRoute = OwnerSetupRouteImport.update({
  id: '/owner-setup',
  path: '/owner-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ZizoRoute = ZizoRouteImport.update({
  id: '/zizo',
  path: '/zizo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBundlesRoute = AdminBundlesRouteImport.update({
  id: '/bundles',
  path: '/bundles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogImportRoute = AdminCatalogImportRouteImport.update({
  id: '/catalog-import',
  path: '/catalog-import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeliveryRoute = AdminDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromotionsRoute = AdminPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperIndexRoute = DeveloperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeveloperRoute,
} as any)
const DeveloperNewRoute = DeveloperNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DeveloperRoute,
} as any)
const PosIndexRoute = PosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PosRoute,
} as any)
const PosCustomersRoute = PosCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => PosRoute,
} as any)
const PosInventoryRoute = PosInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => PosRoute,
} as any)
const PosInvoicesRoute = PosInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => PosRoute,
} as any)
const PosPurchasesRoute = PosPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => PosRoute,
} as any)
const PosReportsRoute = PosReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PosRoute,
} as any)
const PosSuppliersRoute = PosSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => PosRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SStoreSlugRoute = SStoreSlugRouteImport.update({
  id: '/s/$storeSlug',
  path: '/s/$storeSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackTokenRoute = TrackTokenRouteImport.update({
  id: '/track/$token',
  path: '/track/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCatalogIdRoute = AdminCatalogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCatalogRoute,
} as any)
const AdminOrdersTokenRoute = AdminOrdersTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const DeveloperStoresIndexRoute = DeveloperStoresIndexRouteImport.update({
  id: '/stores/',
  path: '/stores/',
  getParentRoute: () => DeveloperRoute,
} as any)
const DeveloperStoresIdRoute = DeveloperStoresIdRouteImport.update({
  id: '/stores/$id',
  path: '/stores/$id',
  getParentRoute: () => DeveloperRoute,
} as any)
const OrderPendingTokenRoute = OrderPendingTokenRouteImport.update({
  id: '/order/pending/$token',
  path: '/order/pending/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SStoreSlugIndexRoute = SStoreSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SStoreSlugRoute,
} as any)
const SStoreSlugAdminRoute = SStoreSlugAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => SStoreSlugRoute,
} as any)
const SStoreSlugCartRoute = SStoreSlugCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => SStoreSlugRoute,
} as any)
const SStoreSlugCheckoutRoute = SStoreSlugCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => SStoreSlugRoute,
} as any)
const ApiPublicProductImageIdRoute = ApiPublicProductImageIdRouteImport.update({
  id: '/api/public/product-image/$id',
  path: '/api/public/product-image/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStoreLogoIdRoute = ApiPublicStoreLogoIdRouteImport.update({
  id: '/api/public/store-logo/$id',
  path: '/api/public/store-logo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SStoreSlugAdminIndexRoute = SStoreSlugAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SStoreSlugAdminRoute,
} as any)
const SStoreSlugAdminAnnouncementsRoute =
  SStoreSlugAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => SStoreSlugAdminRoute,
  } as any)
const SStoreSlugAdminCatalogRoute = SStoreSlugAdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => SStoreSlugAdminRoute,
} as any)
const SStoreSlugAdminDeliveryRoute = SStoreSlugAdminDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => SStoreSlugAdminRoute,
} as any)
const SStoreSlugAdminOrdersRoute = SStoreSlugAdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SStoreSlugAdminRoute,
} as any)
const SStoreSlugAdminReportsRoute = SStoreSlugAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => SStoreSlugAdminRoute,
} as any)
const SStoreSlugAdminSettingsRoute = SStoreSlugAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SStoreSlugAdminRoute,
} as any)
const SStoreSlugAdminTeamRoute = SStoreSlugAdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => SStoreSlugAdminRoute,
} as any)
const SStoreSlugAdminThemeRoute = SStoreSlugAdminThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => SStoreSlugAdminRoute,
} as any)
const SStoreSlugOrderTokenRoute = SStoreSlugOrderTokenRouteImport.update({
  id: '/order/$token',
  path: '/order/$token',
  getParentRoute: () => SStoreSlugRoute,
} as any)
const SStoreSlugProductSlugRoute = SStoreSlugProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => SStoreSlugRoute,
} as any)
const SStoreSlugTrackTokenRoute = SStoreSlugTrackTokenRouteImport.update({
  id: '/track/$token',
  path: '/track/$token',
  getParentRoute: () => SStoreSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/developer': typeof DeveloperRouteWithChildren
  '/freshness': typeof FreshnessRoute
  '/owner-setup': typeof OwnerSetupRoute
  '/pos': typeof PosRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/zizo': typeof ZizoRoute
  '/admin/bundles': typeof AdminBundlesRoute
  '/admin/catalog': typeof AdminCatalogRouteWithChildren
  '/admin/catalog-import': typeof AdminCatalogImportRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/developer/new': typeof DeveloperNewRoute
  '/pos/customers': typeof PosCustomersRoute
  '/pos/inventory': typeof PosInventoryRoute
  '/pos/invoices': typeof PosInvoicesRoute
  '/pos/purchases': typeof PosPurchasesRoute
  '/pos/reports': typeof PosReportsRoute
  '/pos/suppliers': typeof PosSuppliersRoute
  '/product/$slug': typeof ProductSlugRoute
  '/s/$storeSlug': typeof SStoreSlugRouteWithChildren
  '/track/$token': typeof TrackTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/developer/': typeof DeveloperIndexRoute
  '/pos/': typeof PosIndexRoute
  '/admin/catalog/$id': typeof AdminCatalogIdRoute
  '/admin/orders/$token': typeof AdminOrdersTokenRoute
  '/developer/stores/$id': typeof DeveloperStoresIdRoute
  '/order/pending/$token': typeof OrderPendingTokenRoute
  '/s/$storeSlug/admin': typeof SStoreSlugAdminRouteWithChildren
  '/s/$storeSlug/cart': typeof SStoreSlugCartRoute
  '/s/$storeSlug/checkout': typeof SStoreSlugCheckoutRoute
  '/developer/stores/': typeof DeveloperStoresIndexRoute
  '/s/$storeSlug/': typeof SStoreSlugIndexRoute
  '/api/public/product-image/$id': typeof ApiPublicProductImageIdRoute
  '/api/public/store-logo/$id': typeof ApiPublicStoreLogoIdRoute
  '/s/$storeSlug/admin/announcements': typeof SStoreSlugAdminAnnouncementsRoute
  '/s/$storeSlug/admin/catalog': typeof SStoreSlugAdminCatalogRoute
  '/s/$storeSlug/admin/delivery': typeof SStoreSlugAdminDeliveryRoute
  '/s/$storeSlug/admin/orders': typeof SStoreSlugAdminOrdersRoute
  '/s/$storeSlug/admin/reports': typeof SStoreSlugAdminReportsRoute
  '/s/$storeSlug/admin/settings': typeof SStoreSlugAdminSettingsRoute
  '/s/$storeSlug/admin/team': typeof SStoreSlugAdminTeamRoute
  '/s/$storeSlug/admin/theme': typeof SStoreSlugAdminThemeRoute
  '/s/$storeSlug/order/$token': typeof SStoreSlugOrderTokenRoute
  '/s/$storeSlug/product/$slug': typeof SStoreSlugProductSlugRoute
  '/s/$storeSlug/track/$token': typeof SStoreSlugTrackTokenRoute
  '/s/$storeSlug/admin/': typeof SStoreSlugAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/freshness': typeof FreshnessRoute
  '/owner-setup': typeof OwnerSetupRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/zizo': typeof ZizoRoute
  '/admin/bundles': typeof AdminBundlesRoute
  '/admin/catalog': typeof AdminCatalogRouteWithChildren
  '/admin/catalog-import': typeof AdminCatalogImportRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/developer/new': typeof DeveloperNewRoute
  '/pos/customers': typeof PosCustomersRoute
  '/pos/inventory': typeof PosInventoryRoute
  '/pos/invoices': typeof PosInvoicesRoute
  '/pos/purchases': typeof PosPurchasesRoute
  '/pos/reports': typeof PosReportsRoute
  '/pos/suppliers': typeof PosSuppliersRoute
  '/product/$slug': typeof ProductSlugRoute
  '/track/$token': typeof TrackTokenRoute
  '/admin': typeof AdminIndexRoute
  '/developer': typeof DeveloperIndexRoute
  '/pos': typeof PosIndexRoute
  '/admin/catalog/$id': typeof AdminCatalogIdRoute
  '/admin/orders/$token': typeof AdminOrdersTokenRoute
  '/developer/stores/$id': typeof DeveloperStoresIdRoute
  '/order/pending/$token': typeof OrderPendingTokenRoute
  '/s/$storeSlug/cart': typeof SStoreSlugCartRoute
  '/s/$storeSlug/checkout': typeof SStoreSlugCheckoutRoute
  '/developer/stores': typeof DeveloperStoresIndexRoute
  '/s/$storeSlug': typeof SStoreSlugIndexRoute
  '/api/public/product-image/$id': typeof ApiPublicProductImageIdRoute
  '/api/public/store-logo/$id': typeof ApiPublicStoreLogoIdRoute
  '/s/$storeSlug/admin/announcements': typeof SStoreSlugAdminAnnouncementsRoute
  '/s/$storeSlug/admin/catalog': typeof SStoreSlugAdminCatalogRoute
  '/s/$storeSlug/admin/delivery': typeof SStoreSlugAdminDeliveryRoute
  '/s/$storeSlug/admin/orders': typeof SStoreSlugAdminOrdersRoute
  '/s/$storeSlug/admin/reports': typeof SStoreSlugAdminReportsRoute
  '/s/$storeSlug/admin/settings': typeof SStoreSlugAdminSettingsRoute
  '/s/$storeSlug/admin/team': typeof SStoreSlugAdminTeamRoute
  '/s/$storeSlug/admin/theme': typeof SStoreSlugAdminThemeRoute
  '/s/$storeSlug/order/$token': typeof SStoreSlugOrderTokenRoute
  '/s/$storeSlug/product/$slug': typeof SStoreSlugProductSlugRoute
  '/s/$storeSlug/track/$token': typeof SStoreSlugTrackTokenRoute
  '/s/$storeSlug/admin': typeof SStoreSlugAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/developer': typeof DeveloperRouteWithChildren
  '/freshness': typeof FreshnessRoute
  '/owner-setup': typeof OwnerSetupRoute
  '/pos': typeof PosRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/zizo': typeof ZizoRoute
  '/admin/bundles': typeof AdminBundlesRoute
  '/admin/catalog': typeof AdminCatalogRouteWithChildren
  '/admin/catalog-import': typeof AdminCatalogImportRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/developer/new': typeof DeveloperNewRoute
  '/pos/customers': typeof PosCustomersRoute
  '/pos/inventory': typeof PosInventoryRoute
  '/pos/invoices': typeof PosInvoicesRoute
  '/pos/purchases': typeof PosPurchasesRoute
  '/pos/reports': typeof PosReportsRoute
  '/pos/suppliers': typeof PosSuppliersRoute
  '/product/$slug': typeof ProductSlugRoute
  '/s/$storeSlug': typeof SStoreSlugRouteWithChildren
  '/track/$token': typeof TrackTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/developer/': typeof DeveloperIndexRoute
  '/pos/': typeof PosIndexRoute
  '/admin/catalog/$id': typeof AdminCatalogIdRoute
  '/admin/orders/$token': typeof AdminOrdersTokenRoute
  '/developer/stores/$id': typeof DeveloperStoresIdRoute
  '/order/pending/$token': typeof OrderPendingTokenRoute
  '/s/$storeSlug/admin': typeof SStoreSlugAdminRouteWithChildren
  '/s/$storeSlug/cart': typeof SStoreSlugCartRoute
  '/s/$storeSlug/checkout': typeof SStoreSlugCheckoutRoute
  '/developer/stores/': typeof DeveloperStoresIndexRoute
  '/s/$storeSlug/': typeof SStoreSlugIndexRoute
  '/api/public/product-image/$id': typeof ApiPublicProductImageIdRoute
  '/api/public/store-logo/$id': typeof ApiPublicStoreLogoIdRoute
  '/s/$storeSlug/admin/announcements': typeof SStoreSlugAdminAnnouncementsRoute
  '/s/$storeSlug/admin/catalog': typeof SStoreSlugAdminCatalogRoute
  '/s/$storeSlug/admin/delivery': typeof SStoreSlugAdminDeliveryRoute
  '/s/$storeSlug/admin/orders': typeof SStoreSlugAdminOrdersRoute
  '/s/$storeSlug/admin/reports': typeof SStoreSlugAdminReportsRoute
  '/s/$storeSlug/admin/settings': typeof SStoreSlugAdminSettingsRoute
  '/s/$storeSlug/admin/team': typeof SStoreSlugAdminTeamRoute
  '/s/$storeSlug/admin/theme': typeof SStoreSlugAdminThemeRoute
  '/s/$storeSlug/order/$token': typeof SStoreSlugOrderTokenRoute
  '/s/$storeSlug/product/$slug': typeof SStoreSlugProductSlugRoute
  '/s/$storeSlug/track/$token': typeof SStoreSlugTrackTokenRoute
  '/s/$storeSlug/admin/': typeof SStoreSlugAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/delivery'
    | '/developer'
    | '/freshness'
    | '/owner-setup'
    | '/pos'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/zizo'
    | '/admin/bundles'
    | '/admin/catalog'
    | '/admin/catalog-import'
    | '/admin/delivery'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/promotions'
    | '/admin/reports'
    | '/admin/settings'
    | '/category/$slug'
    | '/developer/new'
    | '/pos/customers'
    | '/pos/inventory'
    | '/pos/invoices'
    | '/pos/purchases'
    | '/pos/reports'
    | '/pos/suppliers'
    | '/product/$slug'
    | '/s/$storeSlug'
    | '/track/$token'
    | '/admin/'
    | '/developer/'
    | '/pos/'
    | '/admin/catalog/$id'
    | '/admin/orders/$token'
    | '/developer/stores/$id'
    | '/order/pending/$token'
    | '/s/$storeSlug/admin'
    | '/s/$storeSlug/cart'
    | '/s/$storeSlug/checkout'
    | '/developer/stores/'
    | '/s/$storeSlug/'
    | '/api/public/product-image/$id'
    | '/api/public/store-logo/$id'
    | '/s/$storeSlug/admin/announcements'
    | '/s/$storeSlug/admin/catalog'
    | '/s/$storeSlug/admin/delivery'
    | '/s/$storeSlug/admin/orders'
    | '/s/$storeSlug/admin/reports'
    | '/s/$storeSlug/admin/settings'
    | '/s/$storeSlug/admin/team'
    | '/s/$storeSlug/admin/theme'
    | '/s/$storeSlug/order/$token'
    | '/s/$storeSlug/product/$slug'
    | '/s/$storeSlug/track/$token'
    | '/s/$storeSlug/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/delivery'
    | '/freshness'
    | '/owner-setup'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/zizo'
    | '/admin/bundles'
    | '/admin/catalog'
    | '/admin/catalog-import'
    | '/admin/delivery'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/promotions'
    | '/admin/reports'
    | '/admin/settings'
    | '/category/$slug'
    | '/developer/new'
    | '/pos/customers'
    | '/pos/inventory'
    | '/pos/invoices'
    | '/pos/purchases'
    | '/pos/reports'
    | '/pos/suppliers'
    | '/product/$slug'
    | '/track/$token'
    | '/admin'
    | '/developer'
    | '/pos'
    | '/admin/catalog/$id'
    | '/admin/orders/$token'
    | '/developer/stores/$id'
    | '/order/pending/$token'
    | '/s/$storeSlug/cart'
    | '/s/$storeSlug/checkout'
    | '/developer/stores'
    | '/s/$storeSlug'
    | '/api/public/product-image/$id'
    | '/api/public/store-logo/$id'
    | '/s/$storeSlug/admin/announcements'
    | '/s/$storeSlug/admin/catalog'
    | '/s/$storeSlug/admin/delivery'
    | '/s/$storeSlug/admin/orders'
    | '/s/$storeSlug/admin/reports'
    | '/s/$storeSlug/admin/settings'
    | '/s/$storeSlug/admin/team'
    | '/s/$storeSlug/admin/theme'
    | '/s/$storeSlug/order/$token'
    | '/s/$storeSlug/product/$slug'
    | '/s/$storeSlug/track/$token'
    | '/s/$storeSlug/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/delivery'
    | '/developer'
    | '/freshness'
    | '/owner-setup'
    | '/pos'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/zizo'
    | '/admin/bundles'
    | '/admin/catalog'
    | '/admin/catalog-import'
    | '/admin/delivery'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/promotions'
    | '/admin/reports'
    | '/admin/settings'
    | '/category/$slug'
    | '/developer/new'
    | '/pos/customers'
    | '/pos/inventory'
    | '/pos/invoices'
    | '/pos/purchases'
    | '/pos/reports'
    | '/pos/suppliers'
    | '/product/$slug'
    | '/s/$storeSlug'
    | '/track/$token'
    | '/admin/'
    | '/developer/'
    | '/pos/'
    | '/admin/catalog/$id'
    | '/admin/orders/$token'
    | '/developer/stores/$id'
    | '/order/pending/$token'
    | '/s/$storeSlug/admin'
    | '/s/$storeSlug/cart'
    | '/s/$storeSlug/checkout'
    | '/developer/stores/'
    | '/s/$storeSlug/'
    | '/api/public/product-image/$id'
    | '/api/public/store-logo/$id'
    | '/s/$storeSlug/admin/announcements'
    | '/s/$storeSlug/admin/catalog'
    | '/s/$storeSlug/admin/delivery'
    | '/s/$storeSlug/admin/orders'
    | '/s/$storeSlug/admin/reports'
    | '/s/$storeSlug/admin/settings'
    | '/s/$storeSlug/admin/team'
    | '/s/$storeSlug/admin/theme'
    | '/s/$storeSlug/order/$token'
    | '/s/$storeSlug/product/$slug'
    | '/s/$storeSlug/track/$token'
    | '/s/$storeSlug/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  DeliveryRoute: typeof DeliveryRoute
  DeveloperRoute: typeof DeveloperRouteWithChildren
  FreshnessRoute: typeof FreshnessRoute
  OwnerSetupRoute: typeof OwnerSetupRoute
  PosRoute: typeof PosRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  ZizoRoute: typeof ZizoRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  SStoreSlugRoute: typeof SStoreSlugRouteWithChildren
  TrackTokenRoute: typeof TrackTokenRoute
  OrderPendingTokenRoute: typeof OrderPendingTokenRoute
  ApiPublicProductImageIdRoute: typeof ApiPublicProductImageIdRoute
  ApiPublicStoreLogoIdRoute: typeof ApiPublicStoreLogoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freshness': {
      id: '/freshness'
      path: '/freshness'
      fullPath: '/freshness'
      preLoaderRoute: typeof FreshnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner-setup': {
      id: '/owner-setup'
      path: '/owner-setup'
      fullPath: '/owner-setup'
      preLoaderRoute: typeof OwnerSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zizo': {
      id: '/zizo'
      path: '/zizo'
      fullPath: '/zizo'
      preLoaderRoute: typeof ZizoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bundles': {
      id: '/admin/bundles'
      path: '/bundles'
      fullPath: '/admin/bundles'
      preLoaderRoute: typeof AdminBundlesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalog-import': {
      id: '/admin/catalog-import'
      path: '/catalog-import'
      fullPath: '/admin/catalog-import'
      preLoaderRoute: typeof AdminCatalogImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/delivery': {
      id: '/admin/delivery'
      path: '/delivery'
      fullPath: '/admin/delivery'
      preLoaderRoute: typeof AdminDeliveryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promotions': {
      id: '/admin/promotions'
      path: '/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AdminPromotionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/': {
      id: '/developer/'
      path: '/'
      fullPath: '/developer/'
      preLoaderRoute: typeof DeveloperIndexRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/developer/new': {
      id: '/developer/new'
      path: '/new'
      fullPath: '/developer/new'
      preLoaderRoute: typeof DeveloperNewRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/pos/': {
      id: '/pos/'
      path: '/'
      fullPath: '/pos/'
      preLoaderRoute: typeof PosIndexRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/customers': {
      id: '/pos/customers'
      path: '/customers'
      fullPath: '/pos/customers'
      preLoaderRoute: typeof PosCustomersRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/inventory': {
      id: '/pos/inventory'
      path: '/inventory'
      fullPath: '/pos/inventory'
      preLoaderRoute: typeof PosInventoryRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/invoices': {
      id: '/pos/invoices'
      path: '/invoices'
      fullPath: '/pos/invoices'
      preLoaderRoute: typeof PosInvoicesRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/purchases': {
      id: '/pos/purchases'
      path: '/purchases'
      fullPath: '/pos/purchases'
      preLoaderRoute: typeof PosPurchasesRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/reports': {
      id: '/pos/reports'
      path: '/reports'
      fullPath: '/pos/reports'
      preLoaderRoute: typeof PosReportsRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/suppliers': {
      id: '/pos/suppliers'
      path: '/suppliers'
      fullPath: '/pos/suppliers'
      preLoaderRoute: typeof PosSuppliersRouteImport
      parentRoute: typeof PosRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$storeSlug': {
      id: '/s/$storeSlug'
      path: '/s/$storeSlug'
      fullPath: '/s/$storeSlug'
      preLoaderRoute: typeof SStoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$token': {
      id: '/track/$token'
      path: '/track/$token'
      fullPath: '/track/$token'
      preLoaderRoute: typeof TrackTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/catalog/$id': {
      id: '/admin/catalog/$id'
      path: '/$id'
      fullPath: '/admin/catalog/$id'
      preLoaderRoute: typeof AdminCatalogIdRouteImport
      parentRoute: typeof AdminCatalogRoute
    }
    '/admin/orders/$token': {
      id: '/admin/orders/$token'
      path: '/$token'
      fullPath: '/admin/orders/$token'
      preLoaderRoute: typeof AdminOrdersTokenRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/developer/stores/': {
      id: '/developer/stores/'
      path: '/stores'
      fullPath: '/developer/stores/'
      preLoaderRoute: typeof DeveloperStoresIndexRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/developer/stores/$id': {
      id: '/developer/stores/$id'
      path: '/stores/$id'
      fullPath: '/developer/stores/$id'
      preLoaderRoute: typeof DeveloperStoresIdRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/order/pending/$token': {
      id: '/order/pending/$token'
      path: '/order/pending/$token'
      fullPath: '/order/pending/$token'
      preLoaderRoute: typeof OrderPendingTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$storeSlug/': {
      id: '/s/$storeSlug/'
      path: '/'
      fullPath: '/s/$storeSlug/'
      preLoaderRoute: typeof SStoreSlugIndexRouteImport
      parentRoute: typeof SStoreSlugRoute
    }
    '/s/$storeSlug/admin': {
      id: '/s/$storeSlug/admin'
      path: '/admin'
      fullPath: '/s/$storeSlug/admin'
      preLoaderRoute: typeof SStoreSlugAdminRouteImport
      parentRoute: typeof SStoreSlugRoute
    }
    '/s/$storeSlug/cart': {
      id: '/s/$storeSlug/cart'
      path: '/cart'
      fullPath: '/s/$storeSlug/cart'
      preLoaderRoute: typeof SStoreSlugCartRouteImport
      parentRoute: typeof SStoreSlugRoute
    }
    '/s/$storeSlug/checkout': {
      id: '/s/$storeSlug/checkout'
      path: '/checkout'
      fullPath: '/s/$storeSlug/checkout'
      preLoaderRoute: typeof SStoreSlugCheckoutRouteImport
      parentRoute: typeof SStoreSlugRoute
    }
    '/api/public/product-image/$id': {
      id: '/api/public/product-image/$id'
      path: '/api/public/product-image/$id'
      fullPath: '/api/public/product-image/$id'
      preLoaderRoute: typeof ApiPublicProductImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/store-logo/$id': {
      id: '/api/public/store-logo/$id'
      path: '/api/public/store-logo/$id'
      fullPath: '/api/public/store-logo/$id'
      preLoaderRoute: typeof ApiPublicStoreLogoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$storeSlug/admin/': {
      id: '/s/$storeSlug/admin/'
      path: '/'
      fullPath: '/s/$storeSlug/admin/'
      preLoaderRoute: typeof SStoreSlugAdminIndexRouteImport
      parentRoute: typeof SStoreSlugAdminRoute
    }
    '/s/$storeSlug/admin/announcements': {
      id: '/s/$storeSlug/admin/announcements'
      path: '/announcements'
      fullPath: '/s/$storeSlug/admin/announcements'
      preLoaderRoute: typeof SStoreSlugAdminAnnouncementsRouteImport
      parentRoute: typeof SStoreSlugAdminRoute
    }
    '/s/$storeSlug/admin/catalog': {
      id: '/s/$storeSlug/admin/catalog'
      path: '/catalog'
      fullPath: '/s/$storeSlug/admin/catalog'
      preLoaderRoute: typeof SStoreSlugAdminCatalogRouteImport
      parentRoute: typeof SStoreSlugAdminRoute
    }
    '/s/$storeSlug/admin/delivery': {
      id: '/s/$storeSlug/admin/delivery'
      path: '/delivery'
      fullPath: '/s/$storeSlug/admin/delivery'
      preLoaderRoute: typeof SStoreSlugAdminDeliveryRouteImport
      parentRoute: typeof SStoreSlugAdminRoute
    }
    '/s/$storeSlug/admin/orders': {
      id: '/s/$storeSlug/admin/orders'
      path: '/orders'
      fullPath: '/s/$storeSlug/admin/orders'
      preLoaderRoute: typeof SStoreSlugAdminOrdersRouteImport
      parentRoute: typeof SStoreSlugAdminRoute
    }
    '/s/$storeSlug/admin/reports': {
      id: '/s/$storeSlug/admin/reports'
      path: '/reports'
      fullPath: '/s/$storeSlug/admin/reports'
      preLoaderRoute: typeof SStoreSlugAdminReportsRouteImport
      parentRoute: typeof SStoreSlugAdminRoute
    }
    '/s/$storeSlug/admin/settings': {
      id: '/s/$storeSlug/admin/settings'
      path: '/settings'
      fullPath: '/s/$storeSlug/admin/settings'
      preLoaderRoute: typeof SStoreSlugAdminSettingsRouteImport
      parentRoute: typeof SStoreSlugAdminRoute
    }
    '/s/$storeSlug/admin/team': {
      id: '/s/$storeSlug/admin/team'
      path: '/team'
      fullPath: '/s/$storeSlug/admin/team'
      preLoaderRoute: typeof SStoreSlugAdminTeamRouteImport
      parentRoute: typeof SStoreSlugAdminRoute
    }
    '/s/$storeSlug/admin/theme': {
      id: '/s/$storeSlug/admin/theme'
      path: '/theme'
      fullPath: '/s/$storeSlug/admin/theme'
      preLoaderRoute: typeof SStoreSlugAdminThemeRouteImport
      parentRoute: typeof SStoreSlugAdminRoute
    }
    '/s/$storeSlug/order/$token': {
      id: '/s/$storeSlug/order/$token'
      path: '/order/$token'
      fullPath: '/s/$storeSlug/order/$token'
      preLoaderRoute: typeof SStoreSlugOrderTokenRouteImport
      parentRoute: typeof SStoreSlugRoute
    }
    '/s/$storeSlug/product/$slug': {
      id: '/s/$storeSlug/product/$slug'
      path: '/product/$slug'
      fullPath: '/s/$storeSlug/product/$slug'
      preLoaderRoute: typeof SStoreSlugProductSlugRouteImport
      parentRoute: typeof SStoreSlugRoute
    }
    '/s/$storeSlug/track/$token': {
      id: '/s/$storeSlug/track/$token'
      path: '/track/$token'
      fullPath: '/s/$storeSlug/track/$token'
      preLoaderRoute: typeof SStoreSlugTrackTokenRouteImport
      parentRoute: typeof SStoreSlugRoute
    }
  }
}

interface AdminCatalogRouteChildren {
  AdminCatalogIdRoute: typeof AdminCatalogIdRoute
}

const AdminCatalogRouteChildren: AdminCatalogRouteChildren = {
  AdminCatalogIdRoute: AdminCatalogIdRoute,
}

const AdminCatalogRouteWithChildren = AdminCatalogRoute._addFileChildren(
  AdminCatalogRouteChildren,
)

interface AdminOrdersRouteChildren {
  AdminOrdersTokenRoute: typeof AdminOrdersTokenRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersTokenRoute: AdminOrdersTokenRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface AdminRouteChildren {
  AdminBundlesRoute: typeof AdminBundlesRoute
  AdminCatalogRoute: typeof AdminCatalogRouteWithChildren
  AdminCatalogImportRoute: typeof AdminCatalogImportRoute
  AdminDeliveryRoute: typeof AdminDeliveryRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminPromotionsRoute: typeof AdminPromotionsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBundlesRoute: AdminBundlesRoute,
  AdminCatalogRoute: AdminCatalogRouteWithChildren,
  AdminCatalogImportRoute: AdminCatalogImportRoute,
  AdminDeliveryRoute: AdminDeliveryRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminPromotionsRoute: AdminPromotionsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DeveloperRouteChildren {
  DeveloperNewRoute: typeof DeveloperNewRoute
  DeveloperIndexRoute: typeof DeveloperIndexRoute
  DeveloperStoresIdRoute: typeof DeveloperStoresIdRoute
  DeveloperStoresIndexRoute: typeof DeveloperStoresIndexRoute
}

const DeveloperRouteChildren: DeveloperRouteChildren = {
  DeveloperNewRoute: DeveloperNewRoute,
  DeveloperIndexRoute: DeveloperIndexRoute,
  DeveloperStoresIdRoute: DeveloperStoresIdRoute,
  DeveloperStoresIndexRoute: DeveloperStoresIndexRoute,
}

const DeveloperRouteWithChildren = DeveloperRoute._addFileChildren(
  DeveloperRouteChildren,
)

interface PosRouteChildren {
  PosCustomersRoute: typeof PosCustomersRoute
  PosInventoryRoute: typeof PosInventoryRoute
  PosInvoicesRoute: typeof PosInvoicesRoute
  PosPurchasesRoute: typeof PosPurchasesRoute
  PosReportsRoute: typeof PosReportsRoute
  PosSuppliersRoute: typeof PosSuppliersRoute
  PosIndexRoute: typeof PosIndexRoute
}

const PosRouteChildren: PosRouteChildren = {
  PosCustomersRoute: PosCustomersRoute,
  PosInventoryRoute: PosInventoryRoute,
  PosInvoicesRoute: PosInvoicesRoute,
  PosPurchasesRoute: PosPurchasesRoute,
  PosReportsRoute: PosReportsRoute,
  PosSuppliersRoute: PosSuppliersRoute,
  PosIndexRoute: PosIndexRoute,
}

const PosRouteWithChildren = PosRoute._addFileChildren(PosRouteChildren)

interface SStoreSlugAdminRouteChildren {
  SStoreSlugAdminAnnouncementsRoute: typeof SStoreSlugAdminAnnouncementsRoute
  SStoreSlugAdminCatalogRoute: typeof SStoreSlugAdminCatalogRoute
  SStoreSlugAdminDeliveryRoute: typeof SStoreSlugAdminDeliveryRoute
  SStoreSlugAdminOrdersRoute: typeof SStoreSlugAdminOrdersRoute
  SStoreSlugAdminReportsRoute: typeof SStoreSlugAdminReportsRoute
  SStoreSlugAdminSettingsRoute: typeof SStoreSlugAdminSettingsRoute
  SStoreSlugAdminTeamRoute: typeof SStoreSlugAdminTeamRoute
  SStoreSlugAdminThemeRoute: typeof SStoreSlugAdminThemeRoute
  SStoreSlugAdminIndexRoute: typeof SStoreSlugAdminIndexRoute
}

const SStoreSlugAdminRouteChildren: SStoreSlugAdminRouteChildren = {
  SStoreSlugAdminAnnouncementsRoute: SStoreSlugAdminAnnouncementsRoute,
  SStoreSlugAdminCatalogRoute: SStoreSlugAdminCatalogRoute,
  SStoreSlugAdminDeliveryRoute: SStoreSlugAdminDeliveryRoute,
  SStoreSlugAdminOrdersRoute: SStoreSlugAdminOrdersRoute,
  SStoreSlugAdminReportsRoute: SStoreSlugAdminReportsRoute,
  SStoreSlugAdminSettingsRoute: SStoreSlugAdminSettingsRoute,
  SStoreSlugAdminTeamRoute: SStoreSlugAdminTeamRoute,
  SStoreSlugAdminThemeRoute: SStoreSlugAdminThemeRoute,
  SStoreSlugAdminIndexRoute: SStoreSlugAdminIndexRoute,
}

const SStoreSlugAdminRouteWithChildren = SStoreSlugAdminRoute._addFileChildren(
  SStoreSlugAdminRouteChildren,
)

interface SStoreSlugRouteChildren {
  SStoreSlugAdminRoute: typeof SStoreSlugAdminRouteWithChildren
  SStoreSlugCartRoute: typeof SStoreSlugCartRoute
  SStoreSlugCheckoutRoute: typeof SStoreSlugCheckoutRoute
  SStoreSlugIndexRoute: typeof SStoreSlugIndexRoute
  SStoreSlugOrderTokenRoute: typeof SStoreSlugOrderTokenRoute
  SStoreSlugProductSlugRoute: typeof SStoreSlugProductSlugRoute
  SStoreSlugTrackTokenRoute: typeof SStoreSlugTrackTokenRoute
}

const SStoreSlugRouteChildren: SStoreSlugRouteChildren = {
  SStoreSlugAdminRoute: SStoreSlugAdminRouteWithChildren,
  SStoreSlugCartRoute: SStoreSlugCartRoute,
  SStoreSlugCheckoutRoute: SStoreSlugCheckoutRoute,
  SStoreSlugIndexRoute: SStoreSlugIndexRoute,
  SStoreSlugOrderTokenRoute: SStoreSlugOrderTokenRoute,
  SStoreSlugProductSlugRoute: SStoreSlugProductSlugRoute,
  SStoreSlugTrackTokenRoute: SStoreSlugTrackTokenRoute,
}

const SStoreSlugRouteWithChildren = SStoreSlugRoute._addFileChildren(
  SStoreSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  DeliveryRoute: DeliveryRoute,
  DeveloperRoute: DeveloperRouteWithChildren,
  FreshnessRoute: FreshnessRoute,
  OwnerSetupRoute: OwnerSetupRoute,
  PosRoute: PosRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  ZizoRoute: ZizoRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  SStoreSlugRoute: SStoreSlugRouteWithChildren,
  TrackTokenRoute: TrackTokenRoute,
  OrderPendingTokenRoute: OrderPendingTokenRoute,
  ApiPublicProductImageIdRoute: ApiPublicProductImageIdRoute,
  ApiPublicStoreLogoIdRoute: ApiPublicStoreLogoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
