// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ulavzqvuzjnscgpvvsmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsYXZ6cXZ1empuc2NncHZ2c21xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY1OTM3OTIsImV4cCI6MjEwMjE2OTc5Mn0.JuZL1Xs2U2OBDs8RLd0ioHU2xC2wAOdLRi2xMsCM29Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});